# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_gN_mixoA964z-pHitRTUeq-jzgo19PK
"""

import pandas as pd
import matplotlib.pyplot as plt
import nltk
nltk.download('stopwords')
from wordcloud import WordCloud
from textblob import TextBlob
from nltk.corpus import stopwords
from collections import Counter

df = pd.read_excel('/content/dados_pesquisa_satisfação.xlsx')

# Função para análise quantitativa
def analise_quantitativa(coluna):
    media = df[coluna].mean()
    plt.figure(figsize=(10, 6))
    df[coluna].value_counts().sort_index().plot(kind='bar', color='skyblue', edgecolor='black')
    plt.axhline(y=media, color='r', linestyle='-', linewidth=2, label=f'Média: {media:.2f}')
    plt.title(f'Análise Quantitativa de {coluna}')
    plt.xlabel('Valores')
    plt.ylabel('Frequência')
    plt.legend()
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()

# Função para gerar wordcloud a partir de respostas textuais
def gerar_wordcloud(coluna):
    stop_words = set(stopwords.words('portuguese'))
    stop_words.update(['de', 'a', 'o', 'que', 'e', 'do', 'da', 'em', 'um', 'para', 'com', 'nada', 'nao', 'grupo', 'alguns', 'sempre', 'corplaw', 'não', 'uma', 'os', 'no', 'tudo', 'ainda', 'algumas', 'x', 'bem', 'se', 'na', 'por', 'mais', 'as', 'dos', 'como', 'mas', 'ao', 'ele', 'das', 'à', 'seu', 'sua', 'ou'])
    texto = ' '.join(df[coluna].dropna()).lower()
    palavras = [palavra for palavra in texto.split() if palavra not in stop_words]
    contagem_palavras = Counter(palavras)
    palavras_mais_citadas = contagem_palavras.most_common(5)
    wordcloud_input = ' '.join([palavra for palavra, _ in palavras_mais_citadas])
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(wordcloud_input)
    plt.figure(figsize=(10, 7))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.show()

# Função para análise de sentimentos (aproximação simplificada)
def analise_sentimentos(coluna):
    sentimentos = df[coluna].dropna().apply(lambda x: TextBlob(x).sentiment.polarity)
    media_sentimentos = sentimentos.mean()
    if media_sentimentos > 0:
        return "Somos extremamente necessários"
    elif media_sentimentos < 0:
        return "Não somos necessários"
    else:
        return "Somos necessários"

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 1 a 10 quanto nossos clientes recomendam o Corplaw :")
print(analise_quantitativa('1 a 10 quanto recomenda o Corplaw'))

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 1 a 5 quanto nossos clientes estão satisfeito com as demandas : ")
print(analise_quantitativa('1 a 5 quanto está satisfeito com as demandas'))

# Gerando um wordcloud para respostas textuais
# Substitua 'Comentarios_Gerais' pelo nome real da coluna de comentários
print("Como podemos melhorar nossas entregas :")
gerar_wordcloud('o que melhorar')

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 1 a 5 quanto nossos clientes estão satisfeito com o Navegador : ")
print(analise_quantitativa('1 a 5 quanto está satisfeito com o navegador'))

# Gerando um wordcloud para respostas textuais
# Substitua 'Comentarios_Gerais' pelo nome real da coluna de comentários
print("Como nossos clientes veem nossos Navegadores :")
gerar_wordcloud('o que o navegador poderia ser melhor')

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 1 a 5 quanto nossos clientes estão satisfeito com o Raio-X : ")
print(analise_quantitativa('1 a 5 quanto está a satisfação com o raio-x'))

# Gerando um wordcloud para respostas textuais
# Substitua 'Comentarios_Gerais' pelo nome real da coluna de comentários
print("Como vamos melhorar a nossa entrega do Raio-X :")
gerar_wordcloud('o que o raio-x poderia ser melhor')

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 1 a 5 quanto nossos clientes estão satisfeito com o Conselheiro Jurídico : ")
print(analise_quantitativa('1 a 5 quanto está a satisfação com o conselheiro jurídico'))

# Gerando um wordcloud para respostas textuais
# Substitua 'Comentarios_Gerais' pelo nome real da coluna de comentários
print("Como nossos clientes veem nosso serviço de Conselheiros Jurídicos:")
gerar_wordcloud('O que pode melhorar nos Conselheiros Jurídicos?')

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 1 a 5, qual o grau de satisfação com o Time Consultivo : ")
print(analise_quantitativa('De 1 a 5, qual o seu grau de satisfação com o Time Consultivo?'))

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 1 a 5, qual seu grau de satisfação com o Time Trabalhista : ")
print(analise_quantitativa('De 1 a 5, qual o seu grau de satisfação com o Time Trabalhista?'))

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 1 a 5, qual o grau de satisfação com o Time Societário : ")
print(analise_quantitativa('De 1 a 5, qual o seu grau de satisfação com o Time Societário?'))

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 1 a 5, qual o grau de satisfação com o Time Tributário? : ")
print(analise_quantitativa('De 1 a 5, qual o seu grau de satisfação com o Time Tributário?'))

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 1 a 5, qual o grau de satisfação com o Time de Propriedade Intelectual : ")
print(analise_quantitativa('De 1 a 5, qual o seu grau de satisfação com o Time de Propriedade Intelectual?'))

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 1 a 5, qual o seu grau de satisfação com o Time Contencioso Judicial : ")
print(analise_quantitativa('De 1 a 5, qual o seu grau de satisfação com o Time Contencioso Judicial?'))

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 01 a 05, quanto nosso clientes interessariam por uma sequência de Masterclasses em grupo com outras empresas na área trabalhista : ")
print(analise_quantitativa('De 01 a 05, quanto você se interessaria por uma sequência de Masterclasses em grupo com outras empresas na área trabalhista?'))

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 01 a 05, quanto nosso clientes interessariam por uma sequência de Masterclasses em grupo com outras empresas na área societária : ")
print(analise_quantitativa('De 01 a 05, quanto você se interessaria por uma sequência de Masterclasses em grupo com outras empresas na área societária?'))

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 01 a 05, quanto nosso clientes interessariam por uma sequência de Masterclasses em grupo com outras empresas na área de contratos : ")
print(analise_quantitativa('De 01 a 05, quanto você se interessaria por uma sequência de Masterclasses em grupo com outras empresas na área de contratos?'))

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 01 a 05, quanto nosso clientes interessariam por um treinamento exclusivo na área trabalhista : ")
print(analise_quantitativa('De 01 a 05, quanto você se interessaria por um treinamento online exclusivo para a sua empresa na área trabalhista?'))

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 01 a 05, quanto nosso clientes interessariam por um treinamento exclusivo na área societária : ")
print(analise_quantitativa('De 01 a 05, quanto você se interessaria por um treinamento online exclusivo para a sua empresa na área societária?'))

# Realizando a análise quantitativa
# Substitua 'Nota_Conselheiros_Jurídicos' pelo nome real da coluna
print("De 01 a 05, quanto nosso clientes interessariam por um treinamento exclusivo na área de contratos : ")
print(analise_quantitativa('De 01 a 05, quanto você se interessaria por um treinamento online exclusivo para a sua empresa na área de contratos?'))

# Gerando um wordcloud para respostas textuais
# Substitua 'Comentarios_Gerais' pelo nome real da coluna de comentários
print("O que o Corplaw significa : ")
gerar_wordcloud('O que o Corplaw significa')

# Gerando um wordcloud para respostas textuais
# Substitua 'Comentarios_Gerais' pelo nome real da coluna de comentários
print("Quando nossos clientes mais viram valor no Corplaw : ")
gerar_wordcloud('em qual momento você viu valor')

# Gerando um wordcloud para respostas textuais
# Substitua 'Comentarios_Gerais' pelo nome real da coluna de comentários
print("Quando nossos cliente não gostaram da entrega : ")
gerar_wordcloud('em qual momento você não gostou')

# Analisando os sentimentos das respostas subjetivas
# Substitua 'Comentarios_Gerais' pelo nome real da coluna de comentários
print("Quão essencial o Corplaw é para nossos clientes?")
print(analise_sentimentos('Quão essencial o Corplaw é para a sua empresa?'))

